/**
 * TWV-2026-040 — Curated list of vanity-address patterns whose
 * generator class (Profanity and sibling tools) is known to be
 * brute-forceable on consumer hardware within hours.
 *
 * Sources:
 *   - Wintermute Sep 2022 post-mortem: https://medium.com/wintermute-trading/wintermute-hack-recovery-d36b7ad5a63c
 *   - 1inch writeup: https://blog.1inch.io/a-vulnerability-disclosed-in-profanity-an-ethereum-vanity-address-tool/
 *   - Profanity was seeded with a 32-bit Mersenne Twister PRNG; any
 *     32-bit-entropy-class address is recoverable with a ~4 GPU-day
 *     search. We flag both the observed exploit-corpus patterns AND a
 *     structural heuristic (long leading/trailing zero runs).
 *
 * Updated: 2026-04-16 (initial seed).
 *
 * Policy: updates are code PRs, not remote fetches. False positives
 * are acceptable; false negatives are not (per TWV-2026-040 rules).
 */

export type VanityReason =
  | "profanity-long-leading-zeros"
  | "profanity-long-trailing-zeros"
  | "profanity-known-corpus";

export interface VanityPattern {
  reason: VanityReason;
  /**
   * ECMAScript regex matched against the lowercased address
   * (including the `0x` prefix). The `flags` field is permitted if
   * needed; default is no flags.
   */
  regex: RegExp;
  /** Short human-readable description shown in the warning modal. */
  description: string;
}

/**
 * Structural heuristics. Profanity-class generators optimise for long
 * runs of zero nibbles at one end. Seven or more leading zero nibbles
 * (28 bits of "free" structure) places an address squarely inside the
 * 32-bit-seed search space; six is borderline and we still flag.
 *
 * Wintermute's lost address had 4 leading zero BYTES (8 hex zero
 * nibbles) — so the 7-nibble threshold catches that class without
 * being so restrictive that every "0x0" address trips the warning.
 */
const HEURISTIC_PATTERNS: VanityPattern[] = [
  {
    reason: "profanity-long-leading-zeros",
    regex: /^0x0{7,}/,
    description:
      "This address has a long run of leading zeros. Addresses with " +
      "this structure are frequently generated by Profanity-class tools " +
      "whose 32-bit seed is brute-forceable on consumer GPUs.",
  },
  {
    reason: "profanity-long-trailing-zeros",
    regex: /0{7,}$/,
    description:
      "This address has a long run of trailing zeros. Addresses with " +
      "this structure are frequently generated by Profanity-class tools " +
      "whose 32-bit seed is brute-forceable on consumer GPUs.",
  },
];

/**
 * Documented exploit-corpus patterns. These are intentionally narrow
 * regexes matching prefixes seen in the published Profanity corpus /
 * Wintermute post-mortem. Adding an entry here requires a source link
 * in the commit message.
 *
 * Empty on initial seed — the heuristic covers the Wintermute address
 * class. Populate with exact-match regexes as new exploits are
 * published.
 */
const KNOWN_CORPUS_PATTERNS: VanityPattern[] = [];

export const VANITY_PATTERNS: VanityPattern[] = [
  ...HEURISTIC_PATTERNS,
  ...KNOWN_CORPUS_PATTERNS,
];
