/**
 * Vanity-prefix warning modal — TWV-2026-040.
 *
 * Shown during wallet import when `checkVanityPrefixRisk` flags the
 * derived address. The modal is **non-dismissible by tap-outside**;
 * the user must either cancel or tick the acknowledgement checkbox
 * and explicitly tap "Import anyway". No auto-dismiss.
 */

import * as Linking from "expo-linking";
import { AlertTriangle, Check, ExternalLink } from "lucide-react-native";
import React, { useState } from "react";
import { Modal, Pressable, ScrollView, Text, View } from "react-native";
import { VANITY_LEARN_MORE_URL } from "@/services/security/vanityPrefix";

type VanityPrefixWarningModalProps = {
  visible: boolean;
  address: string;
  description: string;
  onCancel: () => void;
  onAcknowledge: () => void;
};

export default function VanityPrefixWarningModal({
  visible,
  address,
  description,
  onCancel,
  onAcknowledge,
}: VanityPrefixWarningModalProps) {
  const [acknowledged, setAcknowledged] = useState(false);

  // Reset the checkbox every time the modal is re-opened. Consent must
  // be fresh per address.
  React.useEffect(() => {
    if (!visible) setAcknowledged(false);
  }, [visible]);

  return (
    <Modal
      transparent
      visible={visible}
      animationType="fade"
      onRequestClose={onCancel}
    >
      <View className="flex-1 bg-black/60 justify-center px-6">
        <View className="bg-light rounded-2xl p-6">
          <View className="items-center mb-4">
            <View className="bg-light-primary-red/10 p-4 rounded-full mb-3">
              <AlertTriangle size={40} color="#c71c4b" strokeWidth={2} />
            </View>
            <Text className="text-light-matte-black font-bold text-xl text-center">
              Address may be unsafe
            </Text>
          </View>

          <ScrollView style={{ maxHeight: 220 }} className="mb-4">
            <Text className="text-light-matte-black/80 text-sm mb-3 leading-5">
              {description}
            </Text>

            <Text className="text-light-matte-black/80 text-sm mb-3 leading-5">
              Derived address:
            </Text>
            <Text
              className="text-light-matte-black font-mono text-xs leading-5 mb-3"
              selectable
            >
              {address}
            </Text>

            <Pressable
              onPress={() =>
                Linking.openURL(VANITY_LEARN_MORE_URL).catch(() => {})
              }
              className="flex-row items-center"
              accessibilityRole="link"
            >
              <Text className="text-light-primary-red text-sm font-medium mr-1">
                Learn more (Wintermute write-up)
              </Text>
              <ExternalLink size={14} color="#c71c4b" />
            </Pressable>
          </ScrollView>

          <Pressable
            onPress={() => setAcknowledged((v) => !v)}
            accessibilityRole="checkbox"
            accessibilityState={{ checked: acknowledged }}
            className="flex-row items-start mb-4"
          >
            <View
              className={`w-5 h-5 rounded border-2 mr-3 mt-0.5 items-center justify-center ${
                acknowledged
                  ? "bg-light-primary-red border-light-primary-red"
                  : "border-light-matte-black/30"
              }`}
            >
              {acknowledged ? <Check size={14} color="#ffffff" /> : null}
            </View>
            <Text className="text-light-matte-black text-sm flex-1 leading-5">
              I understand this address may have been generated by a
              brute-forceable tool and I accept the risk of importing it.
            </Text>
          </Pressable>

          <Pressable
            className={`py-4 rounded-full items-center mb-3 ${
              acknowledged ? "bg-light-primary-red" : "bg-light-primary-red/40"
            }`}
            disabled={!acknowledged}
            onPress={() => {
              if (acknowledged) onAcknowledge();
            }}
            accessibilityState={{ disabled: !acknowledged }}
          >
            <Text className="text-light font-bold text-base">
              Import anyway
            </Text>
          </Pressable>

          <Pressable
            className="bg-light-main-container py-4 rounded-full items-center border border-light-matte-black/10"
            onPress={onCancel}
          >
            <Text className="text-light-matte-black font-medium text-base">
              Cancel import
            </Text>
          </Pressable>
        </View>
      </View>
    </Modal>
  );
}
